### ISSUE TITLE
GradQC hard-codes the input path

### ISSUE THREAD

**Issue by ihnorton** [pnlbwh/SlicerDiffusionQC#10]
- select Test/Baseline/SiemensTrio[].nrrd
- change output directory to /tmp/test
- run `Process`

```

  File "/opt/worksw/Slicer-4.9.0-20181009.app/Contents/Extensions-27464/DiffusionQC/lib/Slicer-4.9/qt-scripted-modules/gradqclib/slicerUserInteraction.py", line 22, in slicerUserInterface
    self.deletion= np.load(os.path.join(self.directory, self.prefix+'_QC.npy'))
  File "/opt/worksw/Slicer-4.9.0-20181009.app/Contents/lib/Python/lib/python2.7/site-packages/numpy-1.13.1-py2.7-macosx-10.9-x86_64.egg/numpy/lib/npyio.py", line 370, in load
    fid = open(file, "rb")
IOError: [Errno 2] No such file or directory: u'/Users/inorton/work/pnl/git/SlicerDiffusionQC/Test/Baseline/SiemensTrio-Syngo2004A-1_QC.npy'
```

`slicerUserInteraction.py", line 22` and other lines close by need to use the *output path* when loading results.

**Comment by ihnorton** [comment]
`self.prefix` is also hard-coded based on `self.dwiPath`, it should be based on the output path parameter.

**Comment by tashrifbillah** [comment]
Can we double check the existence of Baseline folder on your local machine? I don't see any other reason (obvious or subtle).

**Comment by ihnorton** [comment]
The files that need to be reloaded look like `.../Baseline/tmp.npy'` rather than `Baseline/SiemensTrio-Syngo2004A-1_QC.npy'`.

Anyway the extension is [now in Slicer nightly builds](https://github.com/Slicer/ExtensionsIndex/pull/1590) so you can test it and figure out when you get back :)
