### ISSUE TITLE
Switch to release version of pynrrd when available

### ISSUE THREAD

**Issue by ihnorton** [pnlbwh/SlicerDiffusionQC#6]
Currently pinnned to master in SuperBuild/External_python-diffusionqclib.py to get fix below:

https://github.com/mhe/pynrrd/pull/69

**Comment by tashrifbillah** [comment]
Done!

https://github.com/pnlbwh/SlicerDiffusionQC/commit/751667684d2e17372f264a5f76a5c67c02868a28
